### ISSUE TITLE
When I run the curl command in terminal it gives me 401 user unauthenticated error always

### ISSUE THREAD

**Issue by adiahuja07** [pelauimagineering/apple-music-token-generator#14]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 401 
< content-type: application/json; charset=utf-8
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000; includeSubDomains
< date: Thu, 19 Mar 2020 12:14:41 GMT
< x-cache: TCP_MISS from a104-96-169-92.deploy.akamaitechnologies.com (AkamaiGHost/9.9.2.3-28842850) (-)
< 
* Connection #0 to host api.music.apple.com left intact
* Closing connection 0

**Comment by dusterio** [comment]
@adiahuja07 how did you fix it in the end?
