### ISSUE TITLE
Token Only Valid for 12 Hours

### ISSUE THREAD

**Issue by jmschonfeld** [pelauimagineering/apple-music-token-generator#2]
According to the python file, it looks like the developer token is only valid for 12 hours. After about 12 hours, MusicKit begins rejecting my developer token (I get a 401 HTTP error on requests to retrieve a user token). Is this correct? How can I get around this 12 hour time limit?

**Comment by pelauimagineering** [comment]
I don’t think you can. Just write your solution to be ready to refresh the token on demand.

**Comment by prhiggins** [comment]
You can also choose create the token with a different expiration date (up to 6 months ahead).

**Comment by pelauimagineering** [comment]
If I recall correctly, the guidance from the folks at Apple was to use a short expiration period -- presumably for the sake of security.

**Comment by artemmazheykin** [comment]
Could you please give the exemple of how to refresh the token in swift using your python file?
