### ISSUE TITLE
I am getting a 401 error, what would I be doing wrong?

### ISSUE THREAD

**Issue by takasurazeem** [pelauimagineering/apple-music-token-generator#3]

**Comment by pelauimagineering** [comment]
The python script, as written, builds a token with a 12-hour expiration. Your existing token may have expired. 
HTTP 401 means “Unauthorized”

**Comment by takasurazeem** [comment]
I was building a token with expiry of 1 year 😅

**Comment by dusterio** [comment]
@takasurazeem did you find a fix?

**Comment by takasurazeem** [comment]
> @takasurazeem did you find a fix?

I stopped working on the music app @dusterio.
